title: Nguyễn Vũ Bảo
name: Nguyễn Vũ Bảo
description: Blog và portfolio AI Engineer
url: "https://nvbao117.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache

author:
  name: "Nguyễn Vũ Bảo"
  avatar: "/assets/images/avatar.jpg"
  bio: "AI Engineer | NLP | LLM | RAG | MLOps"
  location: "Hồ Chí Minh, Việt Nam"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/nvbao117"

minimal_mistakes_skin: "dark"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
